- superset/assets/src/dashboard/components/Dashboard.jsx
- superset/assets/src/dashboard/components/DashboardBuilder.jsx
- superset/assets/src/dashboard/reducers/getInitialState.js
- superset/assets/src/dashboard/stylesheets/grid.less
- superset/views/core.py
Choose one
- Enhancement (new features, refinement)
> PE-4121 (added charts only mode and remove margin)

- pcv_dashboard.json
- pcv_datasources.yml
Choose one
Updated dashboard styles and dashboard queries
> PCV dash Enhancement

- superset/config.py
Choose one
Set cache `ttl` to 2 hours
> Set cache timing to 2 hours

- pcv_dashboard.json
Choose one
- Added missing trend lines and percentage change in required charts
> PE-4206 PE-4207 Updated dashboards with trend lines and % change

- pcv_dashboard.json
> FIxed top products and top brands query

- superset/custom_auth.py
> PE-4815 (rbac issue for demandai)

- pcv_dashboard.json
Choose one
exclude delete rows while showing aggregations
> PE-4826 ignore deleted rows

- docker_init.sh
- pde_dashboard.json
added PDE docker file
- [x ] Enhancement (new features, refinement)
Added dashboard for PDE 
PDE dashboard is available will with new tenant only
> PE-4537 Added PDE dashboard

- pde_dashboard.json
- superset/models/core.py
> Pe 5191: Handle filter immune slice field change of slice id on import dashboard

- superset/config.py
> PE-5191: Incrementing SUPERSET_WEBSERVER_TIMEOUT to 300

- superset/assets/src/visualizations/FilterBox/FilterBox.jsx
#Commented additional feature
With this change we have removed unused functionality of create and add fields in dropdown 
This changes the also fixes the bug PE-5182 as described in the ticket
> PE-5182 Update FilterBox Component 

- superset/custom_auth.py
> PE-5550: Authorization for solution manager write access

- superset/custom_auth.py
- superset/utils/dashboard_import_export.py
- superset/views/api.py
> PE-5550: publishing dashboard on import

- superset/assets/src/components/FilterableTable/FilterableTableStyles.css
- superset/assets/src/components/VictoryTheme.js
- superset/assets/src/dashboard/components/DashboardBuilder.jsx
- superset/assets/src/dashboard/containers/DashboardBuilder.jsx
- superset/assets/stylesheets/less/cosmo/variables.less
- superset/assets/stylesheets/less/index.less
- superset/assets/stylesheets/superset.less
CSS of superset dashboards will be reflected into iframe
Change Font to peak themes
> (PE-5520, PE-5208)Superset Changes

- superset/views/base.py
- superset/views/core.py
> PE-5798 : Allow peak_user role to edit all charts/dashboards

- superset/assets/src/components/FilterableTable/FilterableTableStyles.css
- superset/assets/src/components/VictoryTheme.js
- superset/assets/src/dashboard/components/DashboardBuilder.jsx
- superset/assets/src/dashboard/containers/DashboardBuilder.jsx
- superset/assets/stylesheets/less/cosmo/variables.less
- superset/assets/stylesheets/less/index.less
- superset/assets/stylesheets/superset.less
- superset/views/base.py
- superset/views/core.py
Description:
- superset chart edit access to peak user
- css changes
> Superset enhancement

- docker_entrypoint.sh
- superset/config.py
- superset/tasks/cache.py
> fixed cache refresh

- superset/config.py
Choose one
Added GB english language and flag selection
None
Check the default flag and language to be GB
> Added GB flag for language selection

- superset/assets/src/customColorSchemes/peak-color-schemes.js
- superset/assets/src/setup/setupColors.js
> PE-6125 Add custom color schemes

- docker_entrypoint.sh
- superset/config.py
- superset/custom_auth.py
- superset/sql_lab.py
- superset/tasks/cache.py
- superset/tasks/schedules.py
- superset/views/core.py
Use Tenant Specific Queue to run celery worker.
> PE-8061 Fix celery worker Queue

- superset/custom_auth.py
Choose one
Fixed RBAC check to be compatible with CODI rebranding work
> PE-8598 Updated check for new CODI rebranding

- Dockerfile
Choose one
Codebuild is giving error on running this command:
curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs
Error message: E: There are problems and -y was used without --force-yes
Fixed command: curl -sL https://deb.nodesource.com/setup_10.x | bash -   && apt-get --force-yes install -y nodejs
> PE-9281: Fix dashboard build error

- requirements/base.txt
- Install prophet package to support forecast in time-series chart
> Added new packages
